2023-11-06 19:10:15,081 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Current SDK version is 0.15.12
2023-11-06 19:10:15,081 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Configure stats pid to 18152
2023-11-06 19:10:15,081 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\.config\wandb\settings
2023-11-06 19:10:15,081 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Loading settings from C:\Users\User\Documents\GitHub\SC2RL\wandb\settings
2023-11-06 19:10:15,081 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2023-11-06 19:10:15,082 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2023-11-06 19:10:15,083 INFO    MainThread:18152 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program_relpath': 'trainppo.py', 'program_abspath': 'c:\\Users\\User\\Documents\\GitHub\\SC2RL\\trainppo.py', 'program': 'c:\\Users\\User\\Documents\\GitHub\\SC2RL\\trainppo.py'}
2023-11-06 19:10:15,084 INFO    MainThread:18152 [wandb_init.py:_log_setup():528] Logging user logs to C:\Users\User\Documents\GitHub\SC2RL\wandb\run-20231106_191015-n0tb56mo\logs\debug.log
2023-11-06 19:10:15,085 INFO    MainThread:18152 [wandb_init.py:_log_setup():529] Logging internal logs to C:\Users\User\Documents\GitHub\SC2RL\wandb\run-20231106_191015-n0tb56mo\logs\debug-internal.log
2023-11-06 19:10:15,086 INFO    MainThread:18152 [wandb_init.py:init():568] calling init triggers
2023-11-06 19:10:15,086 INFO    MainThread:18152 [wandb_init.py:init():575] wandb.init called with sweep_config: {}
config: {'Model': 'v19', 'Machine': 'Main', 'policy': 'MlpPolicy', 'model_save_name': '1699265408'}
2023-11-06 19:10:15,087 INFO    MainThread:18152 [wandb_init.py:init():618] starting backend
2023-11-06 19:10:15,087 INFO    MainThread:18152 [wandb_init.py:init():622] setting up manager
2023-11-06 19:10:15,113 INFO    MainThread:18152 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2023-11-06 19:10:15,119 INFO    MainThread:18152 [wandb_init.py:init():628] backend started and connected
2023-11-06 19:10:15,160 INFO    MainThread:18152 [wandb_init.py:init():720] updated telemetry
2023-11-06 19:10:15,288 INFO    MainThread:18152 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2023-11-06 19:10:16,869 ERROR   MainThread:18152 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-06 19:10:17,870 ERROR   MainThread:18152 [wandb_init.py:init():1188] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 1170, in init
    run = wi.init()
          ^^^^^^^^^
  File "C:\Users\User\AppData\Local\Programs\Python\Python311\Lib\site-packages\wandb\sdk\wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2023-11-06 19:10:19,878 WARNING MsgRouterThr:18152 [router.py:message_loop():77] message_loop has been closed
